version: '3.8'
services:
  dynamodb-admin-demo-aws:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localstack:4566"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    networks:
      - backend
    depends_on:
      - localstack

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_cloud}"
    image: "localstack/localstack:1.3.1"
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - http_proxy=
      - https_proxy=
      - SERVICES=sqs,sns,dynamodb,secretsmanager, ssm
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - SKIP_SSL_CERT_DOWNLOAD=1
      - DISABLE_EVENTS=1
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./setup_aws.sh:/etc/localstack/init/ready.d/setup_aws.sh"
    networks:
      - backend

networks:
  backend: